name: auto update

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master 
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
      - name: Setup config
        run: |
          git config user.name actions
          git config user.email "actions@github.com"
      - name: Run update script
        run: |
          ./update.sh
          git push origin master
